### PR TITLE
youtubeuploader: allow searching video by title

### PR DESCRIPTION
**Pull request by wolfram77**
Hi porjo!

This commit enables searching by video title (with `-title`) when `-filename` is not mentioned.

As i mentioned before, "wikipedia-tts" is a program that crawls wikipedia pages and upload TTS videos to Youtube. It maintains an SQLite database on my computer. However i need to share it with others so they can upload wikipedia TTS videos too (and i can listen to them while doing some exercise).

So it needs to be able to check whether an article has already been uploaded or not. This is what this commit is for.

### CODE REVIEW

**Comment by wolfram77** [comment]
And, i wanted to know what do you do? I am an aspiring engineer and innovator from India. I would love to reduce healthcare costs in my place by starting a fermented food business here (are you interested in cooking too?).

**Comment by porjo** [comment]
@wolfram77 I appreciate your interest and effort, however I'm not sure about this one as it seems quite niche - not many other people would have a use for this. I think it would be better if you forked youtubeuploader and modified it for your needs.

**Comment by wolfram77** [comment]
@porjo Ok thanks for the tip. The feature i want to use does not modify the current syntax. It would only run if "title" was mentioned but not "filename". So i think it is still ok to add to your code. What do you say? Thanks for writing this program, i like it!

**Comment by wolfram77** [comment]
i have been updating youtubeuploader, and in process i think i like the Go philosophy. Build fast and try things. sorry for bothering you if you are busy https://golangf.github.io/youtubeuploader/

**Pull request closed without merging**
